name: Quality

on:
  push:
    branches: [trunk]
  pull_request:

permissions:
  contents: read

jobs:
  php-qa:
    name: PHP QA
    uses: ahegyes/wordpress-configs/.github/workflows/reusable-php-qa.yml@trunk
    with:
      php-version: '8.5'

  deptrac:
    name: Deptrac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: '8.5'
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6
      - run: composer lint:php:deptrac

  changelog:
    name: Changelog fragments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: '8.5'
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6
      - run: composer changelog:validate
