name: Quality

on:
  push:
    branches: [trunk]
  pull_request:

permissions:
  contents: read

jobs:
  lint-php:
    name: Lint PHP
    uses: ahegyes/wordpress-configs/.github/workflows/reusable-php-lint.yml@7c1ef45c6be4cffdea69b05e855ec0c03e51166c
    with:
      scripts: '["lint:php:phpcs", "lint:php:phpstan", "lint:php:deptrac", "lint:php:composer-require-checker", "changelog:validate"]'
