name: Tests

on:
  push:
    branches: [trunk]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    name: Unit
    uses: ahegyes/wordpress-configs/.github/workflows/reusable-phpunit.yml@b63ea7bcb9bb0d64b9499bce9ad4bb396f63b5bd
    with:
      php-version: '8.5'
      composer-script: 'test:unit'
      needs-wp-env: false
